// examples/vue-demo/src/components/GCodePreview.vue
<template>
  <div>
    <canvas ref="preview"></canvas>

    <div>topLayerColor: {{ topLayerColor }}</div>
    <div>lastSegmentColor: {{ lastSegmentColor }}</div>
    <div>endLayer: {{ endLayer }}</div>
    <div>startLayer: {{ startLayer }}</div>
    <div>lineWidth: {{ lineWidth }}</div>
  </div>
</template>

<script>
'use strict';

import * as GCodePreview from 'gcode-preview';
import * as THREE from 'three';

export default {
  props: {
    topLayerColor: String,
    lastSegmentColor: String,
    endLayer: Number,
    startLayer: Number,
    lineWidth: Number
  },

  data() {
    return {
      layerCount: 0
    };
  },

  mounted() {
    this.preview = new GCodePreview.init({
      canvas: this.$refs.preview,
      endLayer: this.endLayer,
      startLayer: this.startLayer,
      topLayerColor: new THREE.Color(this.topLayerColor).getHex(),
      lastSegmentColor: new THREE.Color(this.lastSegmentColor).getHex(),
      lineWidth: this.lineWidth,
      buildVolume: { x: 250, y: 220, z: 150 },
      initialCameraPosition: [0, 400, 450],
      extrusionColor: 'cyan'
    });

    window.addEventListener('resize', () => {
      this.preview.resize();
    });
  },

  methods: {
    processGCode(gcode) {
      this.preview.processGCode(gcode);
      this.layerCount = this.preview.layers.length;
    }
  }
};
</script>
<style scoped>
canvas {
  outline: none;
  width: 100%;
  height: 100%;
}
</style>

// examples/react-typescript-demo/src/components/GCodePreview.tsx
import * as GCodePreview from 'gcode-preview';
import {
  forwardRef,
  Ref,
  useEffect,
  useImperativeHandle,
  useRef,
  useState
} from 'react';
import * as THREE from 'three';

interface GCodePreviewProps {
  topLayerColor?: string;
  lastSegmentColor?: string;
  startLayer?: number;
  endLayer?: number;
  lineWidth?: number;
}

interface GCodePreviewHandle {
  getLayerCount: () => number;
  processGCode: (gcode: string | string[]) => void;
}

function GCodePreviewUI(
  props: GCodePreviewProps,
  ref: Ref<GCodePreviewHandle>
): JSX.Element {
  const {
    topLayerColor = '',
    lastSegmentColor = '',
    startLayer,
    endLayer,
    lineWidth
  } = props;
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [preview, setPreview] = useState<GCodePreview.WebGLPreview>();

  const resizePreview = () => {
    preview?.resize();
  };

  useImperativeHandle(ref, () => ({
    getLayerCount() {
      return preview?.layers.length as number;
    },
    processGCode(gcode) {
      preview?.processGCode(gcode);
    }
  }));

  useEffect(() => {
    setPreview(
      GCodePreview.init({
        canvas: canvasRef.current as HTMLCanvasElement,
        startLayer,
        endLayer,
        lineWidth,
        topLayerColor: new THREE.Color(topLayerColor).getHex(),
        lastSegmentColor: new THREE.Color(lastSegmentColor).getHex(),
        buildVolume: { x: 250, y: 220, z: 150, r: 0, i: 0, j: 0 },
        initialCameraPosition: [0, 400, 450],
        allowDragNDrop: false
      })
    );

    window.addEventListener('resize', resizePreview);

    return () => {
      window.removeEventListener('resize', resizePreview);
    };
  }, []);

  return (
    <div className="gcode-preview">
      <canvas ref={canvasRef}></canvas>

      <div>
        <div>topLayerColor: {topLayerColor}</div>
        <div>lastSegmentColor: {lastSegmentColor}</div>
        <div>startLayer: {startLayer}</div>
        <div>endLayer: {endLayer}</div>
        <div>lineWidth: {lineWidth}</div>
      </div>
    </div>
  );
}

export default forwardRef(GCodePreviewUI);
